name: kampusgo
description: KAMPUSGO - aplikasi mobile manajemen kehidupan kampus untuk mahasiswa.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  flutter_screenutil: ^5.9.3

# Untuk versi produksi selanjutnya bisa ditambahkan Firebase:
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_mewah.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo_mewah.png"
  android_12:
    image: "assets/images/logo_mewah.png"
    icon_background_color: "#000000"
